name: 'The Vinaya Notes Module (VNM) Release Action'
description: 'Creates a .vnm file and a .zip of your module and publishes it as a new GitHub Release.'
inputs:
  path:  # id of input
    description: 'Path to the module folder'
    required: true
    default: 'latest'
  metadata_file:
    description: |
      Path to the metadata yaml file. Defaults to $path/metadata.yaml
      The metadata yaml file must be a dictionaries containing:
        - folder: The name of the module (the folder will get this name in the Vinaya Notebook)
        - description: A short description of the module
      The metadata yaml file may also include:
        - more_info: A link to this module's homepage (it will default to your GitHub repo if not provided)
        - submodules: A list of dictionaries containing:
          - name: The submodule name
          - paths: A list of folders relative to the module root (without leading or trailing slashes)
    required: false
outputs:
  version:
    description: "The released version (without the v: the created release has tag_name with the v)."
    value: ${{ steps.archive.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: setup
      name: Setup the Environment
      shell: bash
      run: |
        echo "MY_WORKING_DIR=${{ runner.temp }}" >> $GITHUB_ENV
        pip install pyyaml
    - id: archive
      name: Setup the archive
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: bash ${{ github.action_path }}/archive.bash "${{ inputs.path }}"
    - name: Write VNM File
      shell: bash
      run: python ${{ github.action_path }}/write_vnm.py "${{ inputs.path }}" --metadata="${{ inputs.metadata_file }}" --repo="${{ github.repository }}" --version="${{ steps.archive.outputs.version }}"
    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.archive.outputs.version }}
        body: |
          Release ${{ steps.archive.outputs.version }}
        draft: false
        prerelease: false
        files: |
          content.zip
          manifest.vnm

