name: 'The Vinaya Notes Module (VNM) Release Action'
description: 'Creates a .vnm file and a .zip of your module and publishes it as a new GitHub Release.'
inputs:
  path:  # id of input
    description: 'Path to the module folder'
    required: true
    default: 'latest'
  metadata_file:
    description: 'Path to the metadata yaml file. Defaults to $path/metadata.yaml'
outputs:
  version:
    description: "The released version (without the v)."
    value: ${{ steps.archive.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: setup
      name: Setup the Environment
      shell: bash
      run: |
        echo "MY_WORKING_DIR=${{ runner.temp }}" >> $GITHUB_ENV
        pip install pyyaml
    - id: archive
      name: Setup the archive
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: bash archive.bash "${{ inputs.path }}"
    - name: Write VNM File
      shell: bash
      run: python write_vnm.py "${{ inputs.path }}" --metadata="${{ inputs.metadata_file }}" --repo="${{ github.repository }}" --version="${{ steps.archive.outputs.version }}"
    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.archive.outputs.version }}
        body: |
          Release ${{ steps.archive.outputs.version }}
        draft: false
        prerelease: false
        files: |
          content.zip
          manifest.vnm

